//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aosch.MES.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActionURL
    {
        public int ID { get; set; }
        public string MenuName { get; set; }
        public string PageLogo { get; set; }
        public int ParentID { get; set; }
        public string URL { get; set; }
        public string Icon { get; set; }
        public int Sort { get; set; }
        public bool Showable { get; set; }
        public string Description { get; set; }
        public bool IsRoot { get; set; }
    }
}
