//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aosch.MES.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string CustomerName { get; set; }
        public string FactoryName { get; set; }
        public string Telphone { get; set; }
        public string Wechat { get; set; }
        public string Email { get; set; }
        public string FactoryAdress { get; set; }
        public string LogoImage { get; set; }
        public string Description { get; set; }
    }
}
